CREATE TABLE `redirect` (
    `redirect_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "短网址唯一id,自增长",
    `long_url` VARCHAR(255) NOT NULL DEFAULT "" COMMENT "原始url|JREAMLU|2016-10-10",
    `short_url` CHAR(25) NOT NULL DEFAULT "" COMMENT "短url|JREAMLU|2016-10-10",
    `long_crc` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "原始url crc|JREAMLU|2016-10-10",
    `short_crc` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "短url crc|JREAMLU|2016-10-10",
    `status` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT "状态 0:删除 1:正常|JREAMLU|2016-10-10",
    `created_by_ip` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "创建者ip|JREAMLU|2016-10-10",
    `updated_by_ip` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "更新者ip|JREAMLU|2016-10-10",
    `created_at` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "创建时间timestamp|JREAMLU|2016-10-10",
    `updated_at` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT "更新时间timestamp|JREAMLU|2016-10-10",
    PRIMARY KEY (`redirect_id`),
    KEY `long_crc` (`long_crc`),
    KEY `short_url` (`short_url`)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COMMENT="基建|短网址表|JREAMLU|2016-10-10";
